spring.application.name=in-sync

# Server
spring.web.error.include-stacktrace=never

# Logging
logging.file.name=logs/in-sync.log
logging.level.root=DEBUG
logging.threshold.file=INFO

# Client
client.url=