#!/usr/bin/env sh
error() {
  printf '\033[1;31m%s\033[0m\n' "$1"
}
success() {
  printf '\033[1;32m%s\033[0m\n' "$1"
}

stash_ref=""

pop_stash() {
  if [ -n "$stash_ref" ]; then
    success "Restoring unstaged/uncommitted changes."
    git stash pop "$stash_ref" || error "Could not apply stashed changes. Please resolve manually."
    stash_ref=""
  fi
}

trap 'pop_stash' EXIT

if ! git diff-index --quiet HEAD -- || [ -n "$(git ls-files --others --exclude-standard)" ]; then
  success "Unstaged/uncommitted changes detected. Stashing changes."
  git stash push -u -m "Stashed changes before push on $(date)." || { error "Failed to stash changes."; exit 1; }
  stash_ref=$(git stash list | head -n 1 | awk -F: '{print $1}')
fi

(
  success "Checking server code."
  cd server || exit 1
  ./mvnw verify || exit 1
) || { error "Server validation failed. See details above."; exit 1; }


(
  success "Checking client code."
  cd client || exit 1
  npm run prettier:check || exit 1
  npm run lint || exit 1
  npm run test:coverage || exit 1
) || { error "Client validation failed. See details above."; exit 1; }


success "All checks passed. Proceeding with push."